### ISSUE TITLE
 Failed to resolve: com.github.shinelw:library:1.0.1 

### ISSUE THREAD

**Issue by Jetereting** [Shinelw/ColorArcProgressBar#1]
Error:(28, 13) Failed to resolve: com.github.shinelw:library:1.0.1
<a href="openFile:D:/WorkSpace/AS_workSpace/Magnetic/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Shinelw** [comment]
oh sorry! My bad! 
I forget to submit the library  into Binary's JCenter.
Now the problem is resolved.
By the way, if you like my first library, give me a star.
Thanks~

**Comment by Jetereting** [comment]
Thanks, I like it. it`s beautiful !

**Comment by Shinelw** [comment]
ahaha~it's my pleasure!
