### ISSUE TITLE
Lint Warning: Avoid object allocations during draw/layout operations (preallocate and reuse instead).

### ISSUE THREAD

**Issue by tankcong** [Shinelw/ColorArcProgressBar#2]
[ColorArcProgressBar#onDraw()](https://github.com/Shinelw/ColorArcProgressBar/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fshinelw%2Flibrary%2FColorArcProgressBar.java#L187)

**Comment by Shinelw** [comment]
Thanks to remind me.
I have modified this.

**Comment by Shinelw** [comment]
if you  like my library, give me a star,please.thanks
